INSERT INTO DISEASES (disease_name, disease_treatment, med_id, doctor_id) VALUES
('Hypertension', 'Antihypertensive medication; reduced salt intake, regular exercise', 1, 56),
('Type 2 Diabetes Mellitus', 'Blood sugar-lowering medication; dietary adjustments', 2, 29),
('Asthma', 'Inhaled bronchodilator; pulmonary rehabilitation', 3, 38),
('Major Depressive Disorder', 'Antidepressant; cognitive behavioral therapy', 4, 62),
('Osteoarthritis', 'NSAID for pain relief; physical therapy', 5, 20),
('Chronic Obstructive Pulmonary Disease', 'Bronchodilators; smoking cessation', 6, 9),
('Coronary Artery Disease', 'Statins; lifestyle changes, angioplasty if needed', 7, 5),
('Rheumatoid Arthritis', 'DMARDs; joint protection, physiotherapy', 8, 13),
('Epilepsy', 'Antiepileptic drugs; ketogenic diet for refractory cases', 9, 57),
('Parkinson\'s Disease', 'Dopaminergic agents; physical therapy', 10, 64),
('Migraine', 'Triptans; avoidance of triggers, regular sleep patterns', 11, 3),
('Anemia', 'Iron supplements; dietary adjustments', 12, 15),
('Hyperlipidemia', 'Statins; dietary changes', 13, 93),
('Hypothyroidism', 'Thyroid hormone replacement', 14, 22),
('Psoriasis', 'Biologics; topical steroids', 15, 87),
('Schizophrenia', 'Antipsychotics; psychotherapy', 16, 28),
('Bipolar Disorder', 'Mood stabilizers; psychoeducation', 17, 35),
('Celiac Disease', 'Avoid gluten; vitamin supplementation', 42, 69),
('Crohn\'s Disease', 'Biologics; dietary management', 18, 16),
('Ulcerative Colitis', 'Aminosalicylates; colectomy for severe cases', 19, 30),
('Hepatitis B', 'Antiviral medication; liver function monitoring', 20, 80),
('Hepatitis C', 'Direct-acting antivirals; avoid alcohol', 21, 54),
('Tuberculosis', 'Antitubercular drugs; adherence to long-term therapy', 22, 63),
('HIV/AIDS', 'Antiretroviral therapy; regular viral load monitoring', 23, 96),
('Lupus', 'Immunosuppressants; regular check-ups', 24, 19),
('Multiple Sclerosis', 'Disease-modifying therapies; physical therapy', 25, 79),
('Kidney Disease', 'Diuretics; blood pressure control', 26, 94),
('Prostate Cancer', 'Hormone therapy; radiation therapy', 27, 49),
('Breast Cancer', 'Hormonal therapy; chemotherapy', 28, 81),
('Skin Cancer', 'Topical therapy; surgical excision for severe cases', 29, 78),
('Osteoporosis', 'Bisphosphonates; calcium and vitamin D supplementation', 30, 76),
('Pneumonia', 'Antibiotics; oxygen therapy if needed', 31, 86),
('Dengue Fever', 'Supportive care; hydration therapy', 32, 6),
('Malaria', 'Antimalarial drugs; insecticide-treated nets', 33, 77),
('Typhoid Fever', 'Antibiotics; fluid replacement therapy', 34, 10),
('Cholera', 'Oral rehydration therapy; antibiotics if needed', 35, 42),
('Leprosy', 'Multidrug therapy; wound care', 36, 59),
('Alzheimer\'s Disease', 'Cholinesterase inhibitors; cognitive stimulation therapies', 37, 2),
('Ebola Virus Disease', 'Fluid resuscitation; electrolyte monitoring', 38, 40),
('Zika Virus', 'Rest; hydration; acetaminophen for pain relief', 39, 1),
('Marburg Virus', 'Isolation; hydration therapy; electrolyte monitoring', 38, 44),
('Yellow Fever', 'Rest; fluids; pain relievers for fever management', 38, 50),
('Anthrax', 'Antibiotics; antitoxin therapy for severe cases', 34, 33),
('Lyme Disease', 'Antibiotics; supportive therapy for chronic symptoms', 43, 17),
('Rabies', 'Post-exposure prophylaxis; wound cleaning', 44, 8),
('Meningitis', 'Antibiotics for bacterial infection; supportive care for viral cases', 45, 97),
('Tetanus', 'Antibiotics; wound cleaning; supportive care', 46, 67),
('Diphtheria', 'Antibiotics; supportive care for respiratory symptoms', 47, 72),
('Pertussis', 'Antibiotics; supportive care to ease coughing', 48, 4),
('Plague', 'Antibiotics; isolation to prevent spread', 49, 55),
('Hookworm', 'Anthelmintics; iron supplementation for anemia', 40, 39),
('Ascariasis', 'Anthelmintic medication; hygiene education', 40, 36),
('Trichinosis', 'Antiparasitic therapy; pain management for muscle symptoms', 40, 68),
('Filariasis', 'Anthelmintic drugs; surgical management for severe lymphedema', 50, 82),
('Onchocerciasis', 'Anthelmintic therapy; management of skin inflammation', 41, 26),
('Hydatid Disease', 'Anthelmintic therapy; surgical removal of cysts', 40, 47);
