INSERT INTO MEDICATIONS (med_name, med_type, med_manufacturer) VALUES
('Amlodipine', 'Antihypertensive', 'Roche'),
('Metformin', 'Antidiabetic', 'AstraZeneca'),
('Albuterol', 'Bronchodilator', 'Takeda'),
('Sertraline', 'Antidepressant', 'Novartis'),
('Ibuprofen', 'Analgesic', 'Amgen'),
('Tiotropium', 'Anticholinergic', 'GlaxoSmithKline'),
('Atorvastatin', 'Statin', 'AstraZeneca'),
('Methotrexate', 'Immunosuppressant', 'Novartis'),
('Levetiracetam', 'Antiepileptic', 'Biogen'),
('Levodopa', 'Dopaminergic', 'Sanofi'),
('Sumatriptan', 'Triptan', 'Johnson & Johnson'),
('Ferrous sulfate', 'Iron supplement', 'Gilead Sciences'),
('Simvastatin', 'Statin', 'Johnson & Johnson'),
('Levothyroxine', 'Thyroid hormone', 'Pfizer'),
('Adalimumab', 'Biologic', 'Bristol-Myers Squibb'),
('Risperidone', 'Antipsychotic', 'Takeda'),
('Lithium', 'Mood stabilizer', 'Bayer'),
('Infliximab', 'Immunosuppressant', 'AstraZeneca'),
('Mesalamine', 'Aminosalicylate', 'Merck'),
('Entecavir', 'Antiviral', 'AstraZeneca'),
('Sofosbuvir', 'Antiviral', 'Merck'),
('Rifampin', 'Antitubercular', 'Teva'),
('Tenofovir', 'Antiviral', 'Gilead Sciences'),
('Hydroxychloroquine', 'Immunosuppressant', 'Novartis'),
('Interferon beta', 'Disease-modifying therapy', 'Bristol-Myers Squibb'),
('Furosemide', 'Diuretic', 'Sanofi'),
('Leuprolide', 'Hormonal therapy', 'Biogen'),
('Tamoxifen', 'Hormonal therapy', 'Amgen'),
('Imiquimod', 'Topical therapy', 'Pfizer'),
('Alendronate', 'Bisphosphonate', 'Novo Nordisk'),
('Amoxicillin', 'Antibiotic', 'Teva'),
('Acetaminophen', 'Analgesic', 'Eli Lilly'),
('Artemether', 'Antimalarial', 'Novartis'),
('Ciprofloxacin', 'Antibiotic', 'Bristol-Myers Squibb'),
('Zinc supplementation', 'Nutritional supplement', 'Takeda'),
('Dapsone', 'Antibiotic', 'Biogen'),
('Donepezil', 'Cognitive enhancer', 'AstraZeneca'),
('Supportive care', 'Supportive therapy', 'N/A'),
('Symptomatic relief', 'Supportive therapy', 'N/A'),
('Albendazole', 'Anthelmintic', 'Bayer'),
('Ivermectin', 'Anthelmintic', 'Amgen'),
('Gluten-free diet', 'Dietary therapy', 'N/A'),
('Doxycycline', 'Antibiotic', 'Novo Nordisk'),
('Rabies immunoglobulin', 'Post-exposure prophylaxis', 'Novo Nordisk'),
('Ceftriaxone', 'Antibiotic', 'Eli Lilly'),
('Tetanus immunoglobulin', 'Post-exposure prophylaxis', 'Pfizer'),
('Diphtheria antitoxin', 'Antitoxin', 'Amgen'),
('Azithromycin', 'Antibiotic', 'AstraZeneca'),
('Streptomycin', 'Antibiotic', 'Johnson & Johnson'),
('Diethylcarbamazine', 'Anthelmintic', 'Takeda');
