-- Use hospitals database
USE hospitals_db;

-- Drop PRESCRIPTIONS table if it already exists
DROP TABLE IF EXISTS PRESCRIPTIONS;

-- Create PRESCRIPTIONS table
CREATE TABLE PRESCRIPTIONS (
    prescription_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  -- Unique prescription ID (auto-incremented)
    prescription_date VARCHAR(10) NOT NULL                    -- Date of the prescription in M/D/Y format
);

-- Load the data from the SQL file generated by the Python script (attached in docs folder)
-- Replace with server/local machine path to the CSV file (e.g. mine was cd ~/Downloads)
-- If this doesn't work, import direct using Terminal:
-- mysql -u root -p hospitals_db < /path/to/insert_prescriptions.sql
SOURCE /path/to/insert_prescriptions.sql;

-- Verify that data was imported successfully
SELECT * FROM PRESCRIPTIONS LIMIT 10;
